# Generated by Django 5.0.7 on 2024-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('LastUpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
